project:
  type: website
  output-dir: docs
  
website:
  title: "Michele Carlin"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
    tools:
      - icon: github
        href: https://github.com/MicheleCarlin/DACSS_604_Assignment4
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2024, Michele Carlin"

format:
  html:
    theme: cerulean
    toc: false
    anchor-sections: false

editor: source

#remember to inlude the following lines to include all files in the `files/` folder that you want to link to.
resources: 
  - "files/**"